workflows:
  maui-ios-build:
    name: .NET MAUI iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        DOTNET_VERSION: "8.0.100"
    scripts:
      - name: Install .NET SDK
        script: |
          curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version $DOTNET_VERSION
          export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
          dotnet --version
      - name: Install MAUI Workload
        script: |
          export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
          dotnet workload install maui
      - name: Restore dependencies
        script: |
          export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
          dotnet restore TruthOrDrink.sln  # No need for cd, it's in the root
      - name: Publish for iOS (Generate IPA)
        script: |
          export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
          dotnet publish TruthOrDrink.sln -f net8.0-ios -c Release /p:Configuration=Release /p:Platform="iPhone" /p:BuildIpa=true /p:RuntimeIdentifier=ios-arm64 /p:OutputPath=$HOME/build_output
          echo "Build completed. Searching for IPA files..."
          find $HOME/build_output -name "*.ipa"
    artifacts:
      - "$HOME/build_output/**/*.ipa"
