workflows:
  maui-ios-build:
    name: .NET MAUI iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        DOTNET_VERSION: "8.0.100"  # Specify the exact .NET version
    scripts:
      - name: Install .NET SDK
        script: |
          curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version $DOTNET_VERSION
          export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
          dotnet --version
      - name: Install MAUI Workload
        script: |
          export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
          dotnet workload install maui
      - name: Restore dependencies
        script: |
          export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
          dotnet restore TruthOrDrinkApp.sln
      - name: Build for iOS
        script: |
          export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
          dotnet build TruthOrDrinkApp.sln -f net8.0-ios -c Release
    artifacts:
      - "TruthOrDrinkApp/bin/Release/net8.0-ios/**/*.ipa"
